baseURL: http://outscal.com/
languageCode: en-us
title: OutScal
theme: hugo-fresh
careerlink: 

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Interview Less, Hire More!
    # Hero subtitle (optional)
    subtitle: We scale high caliber distributed engineering teams with top Indian developers. Outscale your competition by hiring engineers that are right for your team. 
    # Button text
    # button: false
    buttontext: Contact Us
    # Where the main hero button links to
    buttonlink: "#contact"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Hire Developers
    url: "#contact"
  - title: Join Outscal
    url: https://docs.google.com/forms/d/14JviPeV8ZlvTXGQFOY8OXuOrf1FcOqJZ2eo-vWooVRY/
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  # - title: Contact Us
  #   url: /
  #   button: true
  # sidebar:
  #   # Logo (from /images/logos/___.svg)
  #   logo: fresh-square
  #   sections:
  #   - title: User
  #     icon: user
  #     links:
  #     - text: Profile
  #       url: /
  #     - text: Account
  #       url: /
  #     - text: Settings
  #       url: /
  #   - title: Messages
  #     icon: envelope
  #     links:
  #     - text: Inbox
  #       url: /
  #     - text: Compose
  #       url: /
  #   - title: Images
  #     icon: image
  #     links:
  #     - text: Library
  #       url: /
  #     - text: Upload
  #       url: /
  #   - title: Settings
  #     icon: cog
  #     links:
  #     - text: User settings
  #       url: /
  #     - text: App settings
  #       url: /
  section1:
    title: What We Do
    subtitle: We take care of everything so you and your remote engineers can get to building awesome stuff in weeks, not months!
    # We believe best talent is distributed throughout the globe. why isn't your team?
    tiles:
    # - title: Large Talent Pool
    #   icon: mouse-globe
    #   text: India is a market with a large, growing technical talent base, a booming culture of technology and innovation. 
      # url: /
      # buttonText: Free trial
    - title: Elite Selection Process
      icon: laptop-cloud
      text: Only 1 in 50 applicants gets accepted as we test engineers on hard technical and soft skills.
      # url: /
      # buttonText: 
    - title: Rigorous Training
      icon: plug-cloud
      text: All developers go through an intense coding bootcamp while being mentored by senior engineers. 
      # url: /
      # buttonText: Get started
    - title: Distributed Teams
      icon: mouse-globe
      text: We help you setup best practices to ensure seamless communication across your team. 
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Continuous Learning and Development
      text: We provide continuous training to keep our teams’ skills relevant. The more our developers perform for you, the faster we level them up.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Foster Partnerships
      text: We develop relationships with top universities and technical communities to ensure we hire the best of the best.
      icon: doc-sync
    - title: Connecting Teams with Talent
      text: We take a data-driven approach to hiring, developing, and matching developers with our partners.
      icon: mobile-feed
  contact:
    title: "Drop us a line"
    subtitle: "So you can focus on building better products"
    action: https://formspree.io/mayank@outscal.com
    career: https://docs.google.com/forms/d/14JviPeV8ZlvTXGQFOY8OXuOrf1FcOqJZ2eo-vWooVRY/
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  # footer:
  #   # Logo (from /images/logos/___)
  #   # logo: fresh-white-alt.svg
  #   # Social media links (GitHub, Twitter, etc.). All are optional.
  #   socialmedia:
  #   - link: https://github.com/lucperkins/github-fresh
  #     # Icons are from Font Awesome
  #     icon: github
  #   - link: https://dribbble.com/#
  #     icon: dribbble
  #   - link: https://facebook.com/#
  #     icon: facebook
  #   - link: https://twitter.com/lucperkins
  #     icon: twitter
  #   - link: https://bitbucket.org/#
  #     icon: bitbucket
  #   bulmalogo: false
  #   product:
  #   - text: Discover features
  #     link: /
  #   - text: Why choose our product?
  #     link: /
  #   - text: Compare features
  #     link: /
  #   - text: Our roadmap
  #     link: /
  #   - text: Request features
  #     link: /
  #   docs:
  #   - text: Get started
  #     link: /
  #   - text: User guides
  #     link: /
  #   - text: Admin guide
  #     link: /
  #   - text: Developers
  #     link: /
  #   blogroll:
  #   - text: Latest news
  #     link: /
  #   - text: Tech articles
  #     link: /
  #   - text: Video blog
  #     link: /
